# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e16c5dd048781c8361de100c3a2eb76ebcc787708d2aa6ce30acdcd895dfe7c8acd197873bac6485e2a92a43789443db2f78058b33fbbeaa29f25230ee482f75

test:
  secret_key_base: 3ffafa8ed773eb54925678a917c6b0a2518cfc2e97237a51133ccd63d74fffa47e8ede1c80416ce99a5095eb33eaa21a5ce458531ac0ec53c385ee4d69bf96fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
